[[constraint]]
  branch = "master"
  name = "github.com/NVIDIA/go-nvml/pkg/nvml"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
